=== AleksandarVrencev/node_project/oglasi.dtd
<!ELEMENT oglasi (oglas+)>
<!ELEMENT oglas (kategorija,datum_isteka_oglasa,cena,tekst_oglasa,oznaka_oglasa,e_posta)>
<!ELEMENT automobili (#PCDATA)>
<!ELEMENT stanovi (#PCDATA)>
<!ELEMENT alati (#PCDATA)>
<!ELEMENT poducavanje (#PCDATA)>
<!ELEMENT kategorija (automobili|stanovi|alati|poducavanje)>
<!ELEMENT datum_isteka_oglasa (dan,mesec,godina)>
<!ELEMENT dan (#PCDATA)>
<!ELEMENT mesec (#PCDATA)>
<!ELEMENT godina (#PCDATA)>
<!ELEMENT cena (#PCDATA)>
<!ATTLIST cena valuta (dinar|euro|dolar) "dinar">
<!ELEMENT tekst_oglasa (#PCDATA)>
<!ELEMENT oznaka_oglasa (#PCDATA)>
<!ELEMENT e_posta (#PCDATA)>
<!ATTLIST e_posta tip_e_poste (privatna|poslovna) "privatna">

=== AleksandarVrencev/node_project/oglasi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE oglas SYSTEM "oglasi.dtd">
<oglasi xmlns="https://www.w3schools.com" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://www.w3schools.com/xml oglasi.xsd">
    <oglas>
        <kategorija>
            <automobili></automobili>
            <stanovi></stanovi>
            <alati></alati>
            <poducavanje></poducavanje>
        </kategorija>
        <datum_isteka_oglasa>
            <dan></dan>
            <mesec></mesec>
            <godina></godina>
        </datum_isteka_oglasa>
        <cena valuta="dinar"></cena> 
        <tekst_oglasa> 

        </tekst_oglasa>
        <oznaka_oglasa> </oznaka_oglasa>
        <e_posta> </e_posta>
    </oglas> 
</oglasi>
